{% set name = "shortcutter" %}
{% set version = "0.1.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7ae5644e05fbe093b097b3c425230bc14c9c053ef9f51f68767d6bc6cc24c01e

build:
  number: 0
  entry_points:
    - shortcutter = shortcutter:main
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pywin32  # [win]

test:
  imports:
    - shortcutter
  commands:
    - shortcutter --help

about:
  home: https://github.com/kiwi0fruit/shortcutter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Easy cross-platform creation of shortcuts supporting virtual and Anaconda environments (fork of Shortcut)'
  doc_url: https://github.com/kiwi0fruit/shortcutter
  dev_url: https://github.com/kiwi0fruit/shortcutter

extra:
  recipe-maintainers:
    - kiwi0fruit
