{% set name = "sphinxcontrib-restbuilder" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ad2ce3d99384830b136a24b834a1e7aee788918cbcf4eb31a7ee257e5897c6e2

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - sphinx

test:
  imports:
    - sphinxcontrib.writers
    - sphinxcontrib.builders

about:
  home: https://bitbucket.org/birkenfeld/sphinx-contrib
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Sphinx extension to output reST files.'

  description: |
    Sphinx extension to build reST (reStructuredText) files.
    This extension is in particular useful to use in combination with the 
    autodoc extension to automatically generate documentation for use by 
    any rst parser (such as the GitHub wiki). In itself, the extension is 
    fairly straightforward – it takes the parsed reST file from Sphinx and 
    outputs it as reST.
  doc_url: http://pythonhosted.org/sphinxcontrib-restbuilder/
  dev_url: https://bitbucket.org/birkenfeld/sphinx-contrib

extra:
  recipe-maintainers:
    - holgern
    - kiwi0fruit
